name: Build and Deploy
on:
  push:
    branches:
      - deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18


      - name: Install and Build
        run: |
          mv _config_github.yml _config.yml
          npm install
          npm run clean
          npm run build
          cp -r img/* public/img/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          publish_dir: ./public

      # - name: Install and Build
      #   run: |
      #     mv _config_deploy.yml _config.yml
      #     mv public codefish

      # - name: FTP Deploy
      #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
      #   with:
      #     server: ${{ secrets.ftp_server }}
      #     username: ${{ secrets.ftp_user }}
      #     password: ${{ secrets.ftp_pwd }}
      #     local-dir: ./codefish/
      #     server-dir: /var/www/html/codefish/
      #     dangerous-clean-slate: true


